"""Standalone HTML design report."""
from __future__ import annotations

from html import escape
from pathlib import Path

from filter_design.analysis.metrics import ResponseMetrics
from filter_design.domain.network import SynthesisResult
from filter_design.domain.specifications import FilterSpecification
from filter_design.formatting import engineering


def export_html(path: str | Path, spec: FilterSpecification, result: SynthesisResult,
                metrics: ResponseMetrics) -> None:
    rows = "".join(
        f"<tr><td>{escape(c.reference)}</td><td>{escape(c.kind.value)}</td>"
        f"<td>{escape(engineering(c.value, c.unit))}</td></tr>"
        for c in result.network.components)
    html = f"""<!doctype html><html><head><meta charset='utf-8'><title>Filter report</title>
<style>body{{font:15px system-ui;max-width:900px;margin:2rem auto;color:#172033}}table{{border-collapse:collapse;width:100%}}td,th{{padding:.5rem;border-bottom:1px solid #ccd5e0;text-align:left}}.ok{{color:#08783e}}.bad{{color:#b42318}}</style></head><body>
<h1>Open Filter Designer report</h1><h2>Specification</h2><ul>
<li>Response: {escape(spec.response.value)}</li><li>Approximation: {escape(spec.approximation.value)}</li>
<li>Order: {result.order}</li><li>Passband: {', '.join(engineering(f, 'Hz') for f in spec.passband_hz)}</li>
<li>Stopband: {', '.join(engineering(f, 'Hz') for f in spec.stopband_hz)}</li></ul>
<h2>Verification</h2><p class='{'ok' if metrics.meets_passband and metrics.meets_stopband else 'bad'}'>
Passband loss: {metrics.worst_passband_loss_db:.3f} dB; stopband attenuation: {metrics.minimum_stopband_attenuation_db:.3f} dB.</p>
<h2>Components</h2><table><thead><tr><th>Reference</th><th>Type</th><th>Value</th></tr></thead><tbody>{rows}</tbody></table>
<p><small>Generated by an independent implementation. Values are ideal and require tolerance/parasitic verification.</small></p></body></html>"""
    Path(path).write_text(html, encoding="utf-8")
