"""Touchstone 1.0 two-port export for reciprocal networks."""
from __future__ import annotations

from pathlib import Path

from filter_design.analysis.response import ResponsePoint


def export_touchstone(path: str | Path, response: list[ResponsePoint], reference_ohm: float) -> None:
    lines = ["! Generated by Open Filter Designer", f"# Hz S RI R {reference_ohm:g}"]
    for p in response:
        lines.append(f"{p.frequency_hz:.12g} {p.s11.real:.12g} {p.s11.imag:.12g} "
                     f"{p.s21.real:.12g} {p.s21.imag:.12g} {p.s12.real:.12g} {p.s12.imag:.12g} "
                     f"{p.s22.real:.12g} {p.s22.imag:.12g}")
    Path(path).write_text("\n".join(lines) + "\n", encoding="ascii")
